
    let categories = {
        motsInvariables:["DOUCEMENT", "GENTIMENT", "PARTICULIEREMENT", "FREQUEMMENT", "AILLEURS","BEAUCOUP",
            "DAVANTAGE", "DORENAVANT", "JUSQUE", "MAINTENANT", "PERSONNE", "TANT MIEUX", "VOLONTIERS",
            "TOUJOURS", "SOUDAIN", "POURQUOI", "PAR-DESSUS"],
        prenomsFeminins:["ARABELLA","ANNABELLE","THERESE","GIOVANNA","MELISSANDRE", "APOLLINE",
        "FRANCESCA","BLANDINE","CAROLINE","GWENAELLE","ABIGAELLE","BERANGERE","ANASTASIA","MATHILDE",
        "BENEDICTE"],
        prenomsMasculins:["ALEXANDRE","VALENTIN","CHRISTOPHE","THEOPHILE","MUSTAPHA", "ZACHARIE",
            "FRANCESCO","WILLIAM","RODRIGUE","CORENTIN","CONSTANTIN","AURELIEN","PATRICK","THIBAULT",
            "LEONARD"],
        viLlesDuMonde:["ADDIS-ABEBA","NEW-YORK","LE HAVRE","AMSTERDAM","LOS ANGELES", "AVIGNON",
                "STOCKHOLM","CALCUTTA","ZAGREB","SALAMANQUE","KUALA LUMPUR","BORDEAUX","EDINBOURGH","TOMBOUCTOU",
                "BUENOS AIRES"],
        fruitsLegumes:["MANGUE","POIREAU","PASTEQUE","TOPINAMBOUR","GROSEILLE","CAROTTE","FENOUIL",
                    "POMME DE TERRE","AUBERGINE","LENTILLES","POIS CHICHE","CHAMPIGNON","OIGNON","NOIX DE COCO",
                    "COURGETTE"]
    }


